export const sampleData = {
    studentList: [
        {
            "user_table_id": "43319",
            "student_id": "IM25STU0003063",
            "is_active": true,
            "name": "Samridhhi sahu",
            "mobile": "9827133567",
            "email": "Monikasahu33567@gmail.com",
            "father_name": "Hemant kumar sahu",
            "mother_name": "Monika sahu",
            "gender": "Female",
            "date_of_birth": "2009-01-05",
            "dob": "05 Jan 2009",
            "father_contact_number": "9424100567",
            "mother_contact_number": "9827133567",
            "whatsapp_number": "9827133567",
            "parent_email": "null",
            "contact_person": "Mother",
            "contact_person_name": null,
            "contact_person_mobile": null,
            "address": "B22 royal green junwani road bhilai",
            "pin_code": "490020",
            "city": "Bhilai",
            "state": "Chhattisgarh",
            "class_name": "11th",
            "education_board": "Cbse",
            "special_concern": "",
            "profile_status": "Completed",
            "signup_date": "21 Nov 2025 06: 57 PM"
        },
        {
            "id": 3077,
            "user_table_id": "43316",
            "student_table_id": "3077",
            "student_id": "IM25STU0003062",
            "is_active": true,
            "name": "Aanya agrawal",
            "mobile": "9826570100",
            "email": "Umeshdagrawal@gmail.com",
            "father_name": "Umesh Agrawal",
            "mother_name": "Pragya Agrawal",
            "gender": "Female",
            "date_of_birth": "2008-07-23",
            "dob": "23 Jul 2008",
            "father_contact_number": "9826570100",
            "mother_contact_number": "null",
            "whatsapp_number": "9826570100",
            "parent_email": "null",
            "contact_person": "Father",
            "contact_person_name": null,
            "contact_person_mobile": null,
            "address": "Villa no 33, Ambience villa, near Fundahar chowk",
            "pin_code": "492015",
            "latitude": "21.2098521",
            "longitude": "81.6870907",
            "city": "Mana Camp",
            "state": "Chhattisgarh",
            "class_name": "12th",
            "class_id": 38,
            "school_name": "Athena world school",
            "education_board": "Cbse",
            "tutor_preference": "Female",
            "teaching_preference": [
                "My Home"
            ],
            "special_concern": "",
            "time_slots_id_list": [
                8
            ],
            "subjects_list": [
                "Physics",
                "Chemistry"
            ],
            "subject_id_list": [
                12,
                13
            ],
            "profile_status": "Active",
            "signup_date": "21 Nov 2025 11: 06 AM",
            "suitable_days": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
            ],
            "hobbies": "",
            "landmark": "Ambience villas",
            "class_mode": "Offline",
            "counselling_status": ""
        },
        {
            "id": 3076,
            "user_table_id": "43311",
            "student_table_id": "3076",
            "student_id": "IM25STU0003061",
            "is_active": true,
            "name": "Neha Nirmalkar",
            "mobile": "5000000116",
            "email": "nirmalkarn037@gmail.com",
            "father_name": "Dilesh Nirmalkar ",
            "mother_name": "Sunita Nirmalkar ",
            "gender": "Female",
            "date_of_birth": "2002-12-13",
            "dob": "13 Dec 2002",
            "father_contact_number": "9827977632",
            "mother_contact_number": "9827977633",
            "whatsapp_number": "9303489549",
            "parent_email": "null",
            "contact_person": "Mother",
            "contact_person_name": null,
            "contact_person_mobile": null,
            "address": "Bhatagao ravatpura phase-2 sai mandir raipur chhattisgarh ",
            "pin_code": "492001",
            "latitude": "null",
            "longitude": "null",
            "city": "Raipur",
            "state": "Chhattisgarh",
            "class_name": "12th",
            "class_id": 38,
            "school_name": "Nutan higher secondary school ",
            "education_board": "Cgbsc",
            "tutor_preference": "Female",
            "teaching_preference": [
                "Tutor's Home",
                "Tuition Center"
            ],
            "special_concern": "",
            "time_slots_id_list": [
                13,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
                23
            ],
            "subjects_list": [
                "Mathematics"
            ],
            "subject_id_list": [
                2
            ],
            "profile_status": "Completed",
            "signup_date": "20 Nov 2025 01: 39 PM",
            "suitable_days": [
                "Monday",
                "Tuesday",
                "Thursday",
                "Wednesday",
                "Saturday",
                "Friday",
                "Sunday"
            ],
            "hobbies": "Study reading books",
            "landmark": "Bhatagao ravatpura phase-2 ",
            "class_mode": [
                "Online",
                "Offline"
            ],
            "counselling_status": ""
        },
        {
            "id": 3075,
            "user_table_id": "43310",
            "student_table_id": "3075",
            "student_id": "IM25STU0003060",
            "is_active": true,
            "name": "Shivangi Saxena",
            "mobile": "5000000117",
            "email": "saxenashivangi332@gmail.com",
            "father_name": "Shailendra Saxena ",
            "mother_name": "Annu Saxena ",
            "gender": "Female",
            "date_of_birth": "1999-10-25",
            "dob": "25 Oct 1999",
            "father_contact_number": "9890993313",
            "mother_contact_number": "9922679205",
            "whatsapp_number": "7798835471",
            "parent_email": "null",
            "contact_person": "Mother",
            "contact_person_name": null,
            "contact_person_mobile": null,
            "address": "Row house no. 75, Ravi Garden Manjari Bk Solapur road Hadapsar Pune ",
            "pin_code": "412307",
            "latitude": "18.5000732",
            "longitude": "73.963543",
            "city": "Haveli",
            "state": "Maharashtra",
            "class_name": "10th",
            "class_id": 36,
            "school_name": "City International School ",
            "education_board": "CBSE",
            "tutor_preference": "Any",
            "teaching_preference": [
                "My Home"
            ],
            "special_concern": "",
            "time_slots_id_list": [],
            "subjects_list": [
                "Mathematics",
                "Science",
                "Social Science",
                "Hindi",
                "English"
            ],
            "subject_id_list": [
                2,
                4,
                5,
                6,
                7
            ],
            "profile_status": "Completed",
            "signup_date": "20 Nov 2025 12: 30 PM",
            "suitable_days": [
                "Sunday",
                "Saturday"
            ],
            "hobbies": "Reading, Hiking, Sketching ",
            "landmark": "Opp HP petrol pump ",
            "class_mode": "Online",
            "counselling_status": ""
        },
        {
            "id": 3074,
            "user_table_id": "43303",
            "student_table_id": "3074",
            "student_id": "IM25STU0003059",
            "is_active": true,
            "name": "Spandan Gaikwad ",
            "mobile": "8459510473",
            "email": "truptijadhavgaikwad@gmail.com",
            "father_name": "Shashank Gaikwad ",
            "mother_name": "Trupti Gaikwad",
            "gender": "Male",
            "date_of_birth": "2014-09-22",
            "dob": "22 Sep 2014",
            "father_contact_number": "8788658456",
            "mother_contact_number": "8459510473",
            "whatsapp_number": "8888975454",
            "parent_email": "null",
            "contact_person": "Mother",
            "contact_person_name": null,
            "contact_person_mobile": null,
            "address": "Rakshak Nagar Phase 1",
            "pin_code": "411014",
            "latitude": "null",
            "longitude": "null",
            "city": "Pune City",
            "state": "Maharashtra",
            "class_name": "5th",
            "class_id": 31,
            "school_name": "Wisdom world school Hadapsar",
            "education_board": "Icsc",
            "tutor_preference": "Any",
            "teaching_preference": [
                "My Home"
            ],
            "special_concern": "No hitting.screaming.",
            "time_slots_id_list": [
                7,
                8,
                17,
                18
            ],
            "subjects_list": [
                "All Subjects"
            ],
            "subject_id_list": [
                1
            ],
            "profile_status": "Active",
            "signup_date": "19 Nov 2025 04: 48 PM",
            "suitable_days": [
                "Wednesday",
                "Thursday",
                "Monday",
                "Tuesday",
                "Friday",
                "Saturday"
            ],
            "hobbies": "Playing ",
            "landmark": "Rakshak Nagar kharadi",
            "class_mode": "Offline",
            "counselling_status": ""
        },
        {
            "id": 3073,
            "user_table_id": "43296",
            "student_table_id": "3073",
            "student_id": "IM25STU0003058",
            "is_active": true,
            "name": "Shubhangi",
            "mobile": "5000000115",
            "email": "Shubhangigadare@gmail.com",
            "father_name": "-",
            "mother_name": "-",
            "gender": "Female",
            "date_of_birth": "1994-03-22",
            "dob": "22 Mar 1994",
            "father_contact_number": "8605221791",
            "mother_contact_number": "9096456533",
            "whatsapp_number": "9284439869",
            "parent_email": "null",
            "contact_person": "Other",
            "contact_person_name": "Swapnil",
            "contact_person_mobile": "9096456533",
            "address": "Anand park, near oxygen valley manjari budruk",
            "pin_code": "412307",
            "latitude": "18.521266",
            "longitude": "73.98257339999999",
            "city": "Haveli",
            "state": "Maharashtra",
            "class_name": "",
            "class_id": "",
            "school_name": null,
            "education_board": null,
            "tutor_preference": "",
            "teaching_preference": [],
            "special_concern": "",
            "time_slots_id_list": [],
            "subjects_list": [],
            "subject_id_list": [],
            "profile_status": "Incomplete",
            "signup_date": "18 Nov 2025 11: 57 PM",
            "suitable_days": [],
            "hobbies": "",
            "landmark": "Manjari budruk",
            "class_mode": [],
            "counselling_status": ""
        },
        {
            "id": 3072,
            "user_table_id": "43294",
            "student_table_id": "3072",
            "student_id": "IM25STU0003057",
            "is_active": true,
            "name": "Anuj chitmitwar",
            "mobile": "5000000114",
            "email": "anujchitmitwar3333@gmail.com",
            "father_name": "Ajay chitmitwar",
            "mother_name": "Kalpna chitmitwar",
            "gender": "Male",
            "date_of_birth": "1995-09-25",
            "dob": "25 Sep 1995",
            "father_contact_number": "9300624264",
            "mother_contact_number": "null",
            "whatsapp_number": "6260130069",
            "parent_email": "null",
            "contact_person": "Father",
            "contact_person_name": null,
            "contact_person_mobile": null,
            "address": "Bhatagaon Shivam vihar near chandra town",
            "pin_code": "492001",
            "latitude": "null",
            "longitude": "null",
            "city": "Raipur",
            "state": "Chhattisgarh",
            "class_name": "12th",
            "class_id": 38,
            "school_name": "Holy cross Byron bazar Raipur",
            "education_board": "CBSE",
            "tutor_preference": "Male",
            "teaching_preference": [
                "Tutor's Home",
                "Coaching Center"
            ],
            "special_concern": "",
            "time_slots_id_list": [
                11,
                16,
                17,
                21,
                22
            ],
            "subjects_list": [
                "Mathematics",
                "Physics"
            ],
            "subject_id_list": [
                2,
                12
            ],
            "profile_status": "Completed",
            "signup_date": "18 Nov 2025 06: 44 PM",
            "suitable_days": [
                "Monday",
                "Tuesday",
                "Thursday",
                "Wednesday",
                "Saturday",
                "Friday"
            ],
            "hobbies": "",
            "landmark": "Shivam vihar bhatagaon",
            "class_mode": "Offline",
            "counselling_status": ""
        }
    ]
} as const;
export default sampleData;
